name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "hola mundo"
      - name: multiline commands
        run: |
          node -v
          npm -v
      - name: python Commands
        run: |
          import platform
          print(platform.processor())
        shell: python
        